### ISSUE TITLE
Great! that I found this - a question

### ISSUE THREAD

**Issue by shirtsofholl** [develodesign/magento-google-trusted-stores#10]
What does the extension do or do not do? Maybe you can addd some indications to help 

I also see some paid version and although we love github and collaborating and improving it is not clear what is "in" one version or the other

See
https://www.magentocommerce.com/magento-connect/google-trusted-stores.html
https://www.magentocommerce.com/magento-connect/google-trusted-stores-for-magento.html

thanks!

**Comment by yodaddyp** [comment]
Hi.

Our extension has nothing to do with either of those extensions hosted on Magento Connect, so I cannot tell you what they do or do not do.

Thanks
