### ISSUE TITLE
Value for Badge Position is invalid: “” - in multistore

### ISSUE THREAD

**Issue by shirtsofholl** [develodesign/magento-google-trusted-stores#11]
JS var gts=gts||[];gts.push(['id','643262']);gts.push(['badge_position','']);

Error from Google

Value for Badge Position is invalid: “”
How to Fix: The “badge_position” variable of the Google Trusted Stores badge code must be one of the following values: “BOTTOM_LEFT”, “BOTTOM_RIGHT” and “USER_DEFINED”.
Your value: “”.

![image](https://cloud.githubusercontent.com/assets/11224809/12123964/21f36632-b3e4-11e5-8c7c-8d3b3471ceea.png)

**Comment by shirtsofholl** [comment]
Also fixed: looks like default value during set-up is not correct

We had to go back to default config

change value 
then save
change value 
then save again

then it worked

**Comment by yodaddyp** [comment]
Thanks for finding this. I cannot prioritise this as we have a lot of work on and as you have pointed out there is a work around. We will update it when we next work on the plugin, unless you want to submit a pull request :-)
