### ISSUE TITLE
Warning: product id missing

### ISSUE THREAD

**Issue by shirtsofholl** [develodesign/magento-google-trusted-stores#12]
hi, when installing and testing we get the warning product id missing on home page. This seems logical. 

But is there no alternative to let google know this is not a product page? I suspect then we would have this issue on all CMS and blog pages too .... which is not necesary

**Comment by yodaddyp** [comment]
As you have pointed out his is a warning only on the google trusted stores side, and will not effect the extension in anyway.

If you have a solution that will fix this warning, then feel free to submit a pull request.
